# Generated by Django 3.2.6 on 2021-08-20 12:26

from django.db import migrations
import gnd.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gnd_gnd_id',
            field=gnd.fields.GndField(blank=True, max_length=250, null=True),
        ),
    ]
