# Generated by Django 3.2.6 on 2021-08-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_person_gnd_gnd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gnd_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gnd_pref_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
