# Generated by Django 3.2.6 on 2021-08-21 09:00

from django.db import migrations
import gnd.fields


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_person_gnd_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gnd_gnd_id',
            field=gnd.fields.GndField(blank=True, null=True, unique=True),
        ),
    ]
