# Generated by Django 3.2.6 on 2021-08-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_person_gnd_gnd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gnd_birth_date_written',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gnd_death_date_written',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
