# Generated by Django 3.2.6 on 2021-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_auto_20210821_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gnd_gender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
